the TypeError 'buildColumn is not a function.' is fixed. Added  states in the Option.js and also added a 'Update' button.  The states change in the ServerOption.js.